color = input("Enter your favorite color: ")
plural_noun = input("Enter a plural noun: ")
celeberity = input("Enter your favorite celebrity: ")
print("Roses are " + color)
print( plural_noun +" are blue")
print("I love " + celeberity + "and so do you." )